'use strict';

/**
 * src/routes/weeklyReview.js
 *
 * Weekly Spiritual Review — a short AI-generated reflection on the user's
 * past week (Monday-Sunday), generated lazily on request and also
 * pre-generated by a daily cron job (src/jobs/weeklyReviewJob.js) so it's
 * typically already waiting for the user by the time they open the app
 * on Sunday.
 */

const express = require('express');
const { body, validationResult } = require('express-validator');
const prisma = require('../config/prisma');
const { openAIRequest, extractReply } = require('../services/openaiClient');

const router = express.Router();

function validate(req, res) {
  const errors = validationResult(req);
  if (!errors.isEmpty()) { res.status(422).json({ message: errors.array()[0].msg }); return true; }
  return false;
}

// The week being reviewed is the most recently completed (or completing,
// if today is Sunday) Monday-Sunday period.
function currentReviewWeek(date = new Date()) {
  const d = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
  const day = d.getUTCDay(); // 0 = Sunday, 1 = Monday, ...
  const daysSinceSunday = day; // if today is Sunday, this is 0
  const weekEnd = new Date(d);
  weekEnd.setUTCDate(d.getUTCDate() - daysSinceSunday); // most recent Sunday (today if Sunday)
  const weekStart = new Date(weekEnd);
  weekStart.setUTCDate(weekEnd.getUTCDate() - 6); // Monday before that Sunday

  return {
    weekStartDate: weekStart.toISOString().split('T')[0],
    weekEndDate: weekEnd.toISOString().split('T')[0],
  };
}

async function gatherWeekStats(userId, weekStartDate, weekEndDate) {
  const start = new Date(`${weekStartDate}T00:00:00Z`);
  const end = new Date(`${weekEndDate}T23:59:59Z`);

  const [prayers, journalEntries, goalsCompleted, analytics] = await Promise.all([
    prisma.prayer.count({ where: { userId, createdAt: { gte: start, lte: end } } }),
    prisma.journalEntry.count({ where: { userId, createdAt: { gte: start, lte: end } } }),
    prisma.dailyGoal.count({ where: { userId, completed: true, updatedAt: { gte: start, lte: end } } }),
    prisma.analytics.findUnique({ where: { userId } }),
  ]);

  return {
    prayers,
    journalEntries,
    goalsCompleted,
    currentStreak: analytics?.currentStreak || 0,
  };
}

function buildPrompt(stats, language) {
  const isFr = language === 'fr';
  const statsLine = `Prayers this week: ${stats.prayers}. Journal entries: ${stats.journalEntries}. ` +
    `Goals completed: ${stats.goalsCompleted}. Current streak: ${stats.currentStreak} days.`;
  const instructions = isFr
    ? 'Tu es le Compagnon de ReviveSpring, un soutien fidele de l application. A partir des statistiques de la semaine ' +
      'd un utilisateur, ecris une reflexion breve et encourageante (80-130 mots) sur sa semaine spirituelle, en ' +
      'reconnaissant honnetement ce qui a ete accompli (meme si c est peu) et en l encourageant doucement pour la semaine ' +
      'a venir, sans culpabiliser. Renvoie UNIQUEMENT du JSON valide: {"summary":"..."}.'
    : 'You are the ReviveSpring Companion, a faithful supporter of the app. From a user\'s weekly stats, write a brief, ' +
      'encouraging reflection (80-130 words) on their spiritual week, honestly acknowledging what was accomplished (even ' +
      'if modest) and gently encouraging them for the week ahead, without guilt-tripping. Return ONLY valid JSON: ' +
      '{"summary":"..."}.';
  return { instructions, input: [{ role: 'user', content: statsLine }] };
}

function parseSummary(raw) {
  try {
    const cleaned = raw.replace(/```json|```/g, '').trim();
    const parsed = JSON.parse(cleaned);
    if (typeof parsed.summary === 'string' && parsed.summary.trim()) return parsed.summary.trim();
  } catch (_) {
    // fall through
  }
  return raw.trim();
}

async function getOrCreateReview(user, language) {
  const { weekStartDate, weekEndDate } = currentReviewWeek();
  let review = await prisma.weeklyReview.findUnique({
    where: { userId_weekStartDate: { userId: user.id, weekStartDate } },
  });
  if (review) return review;

  const stats = await gatherWeekStats(user.id, weekStartDate, weekEndDate);
  let summary = null;
  try {
    const { instructions, input } = buildPrompt(stats, language);
    const model = process.env.OPENAI_MODEL || 'gpt-5.4-nano';
    const openAIRes = await openAIRequest({ model, instructions, input, max_output_tokens: 260 });
    summary = parseSummary(extractReply(openAIRes));
  } catch (err) {
    console.error('[WEEKLY-REVIEW] AI generation failed:', err.message);
  }

  review = await prisma.weeklyReview.upsert({
    where: { userId_weekStartDate: { userId: user.id, weekStartDate } },
    create: {
      userId: user.id,
      weekStartDate,
      aiSummary: summary,
      stats,
      generatedAt: new Date(),
    },
    update: {},
  });
  return review;
}

function formatReview(review) {
  return {
    id: review.id,
    week_start_date: review.weekStartDate,
    ai_summary: review.aiSummary,
    user_reflection: review.userReflection,
    stats: review.stats,
    generated_at: review.generatedAt,
  };
}

// GET /api/weekly-review — current week's review, generating it if missing
router.get('/', async (req, res, next) => {
  try {
    const language = (req.query.language || req.user.language || 'en').toString();
    const review = await getOrCreateReview(req.user, language);
    res.json(formatReview(review));
  } catch (err) { next(err); }
});

// GET /api/weekly-review/history — past reviews, most recent first
router.get('/history', async (req, res, next) => {
  try {
    const reviews = await prisma.weeklyReview.findMany({
      where: { userId: req.user.id },
      orderBy: { weekStartDate: 'desc' },
      take: 12,
    });
    res.json(reviews.map(formatReview));
  } catch (err) { next(err); }
});

// POST /api/weekly-review/reflection — save the user's own written reflection
router.post('/reflection', [body('reflection').trim().notEmpty()], async (req, res, next) => {
  if (validate(req, res)) return;
  try {
    const language = (req.body.language || req.user.language || 'en').toString();
    const review = await getOrCreateReview(req.user, language);
    const updated = await prisma.weeklyReview.update({
      where: { id: review.id },
      data: { userReflection: req.body.reflection.toString().slice(0, 2000) },
    });
    res.json(formatReview(updated));
  } catch (err) { next(err); }
});

module.exports = router;
module.exports.currentReviewWeek = currentReviewWeek;
module.exports.getOrCreateReview = getOrCreateReview;
